#!/bin/sh
CLASSPATH=src:test:config:data

for f in lib/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done

java -Xmx1G -cp $CLASSPATH jline.ConsoleRunner clojure.main -e "(use '[clojure.contrib.duck-streams :only (spit read-lines reader writer)] '[clojure.contrib def ns-utils pprint repl-utils]) (require '[clojure.contrib.str-utils2 :as s])(set! *print-length* 100)(use 'project-euler)" -r
